# Generated by Django 2.2.16 on 2022-10-06 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20221006_2146'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
